services:
  - type: web
    name: telegram-monitor
    env: python
    region: oregon  # или ближайший
    plan: free      # именно free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -b 0.0.0.0:$PORT
    envVars:
      API_ID:
        fromSecret: API_ID
      API_HASH:
        fromSecret: API_HASH